### ISSUE TITLE
DateTime parsing

### ISSUE THREAD

**Issue by nemanjabodroza** [borisdj/FixedWidthParserWriter#1]
Parsing DateTime with custom format "mm.dd.yyyy" adds 1 minute to resulting value.

**Comment by rparthas** [comment]
@nemanjabodroza  Can you give a sample file and your class  ? I also assume mm.dd.yyyy should be MM.dd.yyyy as small mm reflects minutes.

**Comment by nemanjabodroza** [comment]
it was my mistake with mm instead of MM. Thank you @rparthas
