### ISSUE TITLE
Padding Non Numeric on String

### ISSUE THREAD

**Issue by CosimoPiscopoLutech** [borisdj/FixedWidthParserWriter#16]
It is not possible to add the non numeric pad on string values.

**Comment by borisdj** [comment]
Yes, there is ***PadNonNumeric*** as state in the ReadMe.

**Comment by CosimoPiscopoLutech** [comment]
In FixedWidthParserWriter/FixedWidthBaseProvider.cs you don't initialize the pad variable with the PadNonNumeric property for string.

**Comment by borisdj** [comment]
Added `PadNonNumeric` for String.

**Comment by atosraiprogetti** [comment]
If you want to add it for strings you have to add it inside the `if` before the `switch` `case`.

**Comment by CosimoPiscopoLutech** [comment]
If you want to add it for strings you have to add it inside the `if` before the `switch` `case`.

**Comment by borisdj** [comment]
Fixed.
