### ISSUE TITLE
Parsing a fixed-field-width string with repeating parts

### ISSUE THREAD

**Issue by dinobu** [borisdj/FixedWidthParserWriter#4]
If I have a string containing fixed-field-length fields that are repeating, how can I parse that string line?

For example

<pre>"00050003T3A1111        2999BOSH                          2100021        399APV                           2100022  "</pre>

This string represents fields like:
```
4  byte long message length      ("0005")
4  byte long message id          ("0003")
1  byte long message type        ("T")
1  byte long message sequence    ("3")
8  byte long car Id              ("A1111   ")  
9  byte long part-1 price        ("     2999")
30 byte long part-1 manufacturer ("BOSH                          ")
9  byte long part#               ("2100021  ")
9  byte long part-2 price        ("      399")
30 byte long part-2 manufacturer ("APV                           ")
9  byte long part#               ("2100022  ")
```
Above, fields [part price], [part manufacturer], and [part#] are repeating and could be only 1 tripple or multiple tripples of these.

Also, the part has no decimal.

How would you parse this?  

Obviously, using data model like in your documentation wont work as this data model expects a field to always start at same location; however, repeating fields above start on different locations:

```
public class InvoiceItem
{
    [FixedWidthLineField(Start = 1, Length = 3)]
    public int Number { get; set; }

    [FixedWidthLineField(Start = 4, Length = 1)]
    public string NumberedBullet { get; set; } = ".";

    [FixedWidthLineField(Start = 5, Length = 30)]
    public string Description { get; set; }

    [FixedWidthLineField(Start = 35, Length = 6)]
    public int Quantity { get; set; }

    [FixedWidthLineField(Start = 41, Length = 13)]
    public decimal Price { get; set; }

    [FixedWidthLineField(Start = 54, Length = 13)]
    public decimal Amount => Quantity * Price;
}
```

**Comment by borisdj** [comment]
If number has no decimals at all then just in class model use Property of `int` type.
And if there are decimals but no decimal separator then as stated in README:
 _("0;00" - Special custom Format that removes decimal separator: 123.45 -> 12345)_

As for the data of different length what you could do is to split the list into subLists based on RowLength.
`int rowTypePerNumberOfParts = (RowLentgh - 18 ) / 48;`

Then one options would be make chained Inherited classes and use each subList with proper Model:
```C#
    public class CarPartBase
    {
        [FixedWidthLineField(Start = 1, Length = 4)]
        public int MessageLength { get; set; }

        [FixedWidthLineField(Start = 5, Length = 4)]
        public int MessageId { get; set; }

        [FixedWidthLineField(Start = 9, Length = 1)]
        public string MessageType { get; set; }

        [FixedWidthLineField(Start = 10, Length = 1)]
        public string MessageSequence { get; set; }

        [FixedWidthLineField(Start = 11, Length = 8)]
        public string CarId { get; set; }
    }

    public class CarPart1 : CarPartBase
    {
        [FixedWidthLineField(Start = 19, Length = 9)]
        public decimal PartPrice_1 { get; set; }

        [FixedWidthLineField(Start = 28, Length = 30)]
        public string PartManufacturer_1 { get; set; }

        [FixedWidthLineField(Start = 58, Length = 9)]
        public string PartSharp_1 { get; set; }
    }

    public class CarPart2 : CarPart1
    {
        [FixedWidthLineField(Start = 67, Length = 9)]
        public int PartPrice_2 { get; set; }

        [FixedWidthLineField(Start = 76, Length = 30)]
        public string PartManufacturer_2 { get; set; }

        [FixedWidthLineField(Start = 106, Length = 9)]
        public string PartSharp_2 { get; set; }
    }

    //...
```

Other option could be make to single model with maximum Properties and use multiple Attributes (StructureTypeId per Sublist)
```C#
    public class CarPart
    {
        [FixedWidthLineField(Start = 1, Length = 4, StructureTypeId = 0)]
        [FixedWidthLineField(Start = 1, Length = 4, StructureTypeId = 1)]
        [FixedWidthLineField(Start = 1, Length = 4, StructureTypeId = 2)]
        public int MessageLength { get; set; }

        [FixedWidthLineField(Start = 5, Length = 4, StructureTypeId = 0)]
        [FixedWidthLineField(Start = 5, Length = 4, StructureTypeId = 1)]
        [FixedWidthLineField(Start = 5, Length = 4, StructureTypeId = 2)]
        public int MessageId { get; set; }

        [FixedWidthLineField(Start = 9, Length = 1, StructureTypeId = 0)]
        [FixedWidthLineField(Start = 9, Length = 1, StructureTypeId = 1)]
        [FixedWidthLineField(Start = 9, Length = 1, StructureTypeId = 2)]
        public string MessageType { get; set; }

        [FixedWidthLineField(Start = 10, Length = 1, StructureTypeId = 0)]
        [FixedWidthLineField(Start = 10, Length = 1, StructureTypeId = 1)]
        [FixedWidthLineField(Start = 10, Length = 1, StructureTypeId = 2)]
        public string MessageSequence { get; set; }

        [FixedWidthLineField(Start = 11, Length = 8, StructureTypeId = 0)]
        [FixedWidthLineField(Start = 11, Length = 8, StructureTypeId = 1)]
        [FixedWidthLineField(Start = 11, Length = 8, StructureTypeId = 2)]
        public string CarId { get; set; }

        // Part 1
        [FixedWidthLineField(Start = 19, Length = 9, StructureTypeId = 1)]
        [FixedWidthLineField(Start = 19, Length = 9, StructureTypeId = 2)]
        public decimal PartPrice_1 { get; set; }

        [FixedWidthLineField(Start = 28, Length = 30, StructureTypeId = 1)]
        [FixedWidthLineField(Start = 28, Length = 30, StructureTypeId = 2)]
        public string PartManufacturer_1 { get; set; }

        [FixedWidthLineField(Start = 58, Length = 9, StructureTypeId = 1)]
        [FixedWidthLineField(Start = 58, Length = 9, StructureTypeId = 2)]
        public string PartSharp_1 { get; set; }

        // Part 2
        [FixedWidthLineField(Start = 67, Length = 9, StructureTypeId = 2)]
        public int PartPrice_2 { get; set; }

        [FixedWidthLineField(Start = 76, Length = 30, StructureTypeId = 2)]
        public string PartManufacturer_2 { get; set; }

        [FixedWidthLineField(Start = 106, Length = 9, StructureTypeId = 2)]
        public string PartSharp_2 { get; set; }
    }
```

Depending on situation and maximum number of parts per row decide what is more usefull.
And if there could be a lot of parts, like more then 10 then probably none of these would be practical.
In that case it's maybe better to make a custom parser.

**Comment by dinobu** [comment]
Thanks @borisdj but the problem is that a Car could have one or more parts, meaning using inheritance model and generating a model for each part separately (as you suggested first) or using  a flat model and generating separate property for each field (as you suggested in second) is not practical.

I think this is the result of the fact that this library is *row-centric, you have rows representing each piece of data*.  So, this library expects something like this

```
"00050003T3A1111        2999BOSH                          2100021  "
"00050003T3A1111          399APV                          2100022  "
```

Now you can generate the model since each row has *all* data it needs:

**Length, ID, Type, Sequence, CarId, PartPrice, PartManufacturer, PartId**.  

, that is what I meant by row-centric.

However, in my case, the data is coming from a network stream, so it is continuous string of data like this:

`"00050003T3A1111        2999BOSH                          2100021        399APV                           2100022  "`

, meaning that there is only one row at all time, which is the string of data (or buffer) having:

**Length, ID, Type, Sequence, CarId, _PartPrice, PartManufacturer, PartId, PartPrice, PartManufacturer, PartId, PartPrice, PartManufacturer, PartId, .._.**

, which is not row-centric but has single string having common data for entire string (**Length, ID, Type, Sequence** fields) and repeating portion (**_PartPrice, PartManufacturer, PartId_** fields).

So, yes, it looks like a custom parser is the only option but I was hoping I could find a library that could do this and yours looked promising.

**Comment by borisdj** [comment]
I think you still might be able to use the library with just little preprocessing.
When read gets to PartItems section of string split them into list(each element 48 chars long) and then load into model.
I would make 2 models, one for CarPartHeader and other for CarPartItem:
```C#
public class CarPartHeader
{
	[FixedWidthLineField(Start = 1, Length = 4)]
	public int MessageLength { get; set; }

	[FixedWidthLineField(Start = 5, Length = 4)]
	public int MessageId { get; set; }

	[FixedWidthLineField(Start = 9, Length = 1)]
	public string MessageType { get; set; }

	[FixedWidthLineField(Start = 10, Length = 1)]
	public string MessageSequence { get; set; }

	[FixedWidthLineField(Start = 11, Length = 8)]
	public string CarId { get; set; }
}

public class CarPartItem
{
	[FixedWidthLineField(Start = 1, Length = 9)]
	public decimal PartPrice { get; set; }

	[FixedWidthLineField(Start = 10, Length = 30)]
	public string PartManufacturer { get; set; }

	[FixedWidthLineField(Start = 40, Length = 9)]
	public string PartSharp { get; set; }
}
```

So take first segment(18 chars) of string and read that into CarPartHeader.
Then rest split per 48 chars long subsegment and read those into CarPartItem list.
```
00050003T3A1111        2999BOSH                          2100021        399APV                           2100022  
```
=>
```
"00050003T3A1111   "
"     2999BOSH                          2100021  "
"      399APV                           2100022  "
```

**Comment by dinobu** [comment]
Thanks Boris, I decided to do it myself manualy
