### ISSUE TITLE
Exception on Overflow

### ISSUE THREAD

**Issue by robertoosantos** [borisdj/FixedWidthParserWriter#9]
When I have a property value longer than the lenght, there should be an option if what to get an exception on this.

Ex.:

Property
```
[FixedWidthLineField(Start=1,Length=14)]
public string CNPJ { get; set; }
```

Program
```
        static void Main(string[] args)
        {
            var p = new Pagamento(){CNPJ="123456789012345"};
            var ps = new List<Pagamento>();
            ps.Add(p);
            
            p = new Pagamento(){CNPJ="12345678901234"};
            ps.Add(p);

            var ls = new FixedWidthLinesProvider<Pagamento>().Write(ps);
            
            foreach (var l in ls)
            {
                Console.WriteLine(l);
            }
        }
```

Result
```
12345678901234
12345678901234
```

But there is a data truncation that I may be concerned in some use case.

**Comment by borisdj** [comment]
@robertoosantos Can you resolve conflicts for this PR request.
Or make a new PR with only change of the source for this feature.

**Comment by borisdj** [comment]
Somewhat larger refactor is done.
Latest version now supports Info about trimmed string in List *WarningsLog* of newly added argument ***FixedWidthConfig***.
After reading that you can postProcess throw Exception if needed.

As for your **RecordType** field I think multiple row types in files can be supported even without this element being directly in *FixedWidthAttribute*, simoly by having it be a regular Property in class model.
Or if needed you can send new PR for this only, including Test and ReadMe example for it.

PS Thx for contrib and the initial PullRequest, and sorry for not merging it sooner.
